<Project Sdk="Godot.NET.Sdk/4.7.1">

  <PropertyGroup>
    <Authors>Agus Garcia</Authors>
    <Company>ECS</Company>
    <Description>Ready-to-use ECS components for Godot 4 — velocity, rotation, height, and state machine.</Description>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>14.0</LangVersion>
    <Nullable>enable</Nullable>
    <PackageId>ECS.Components</PackageId>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/agusmgarcia/godot-ecs</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <RootNamespace>ECS.Components</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
    <Version>0.1.0</Version>
    <WarningsAsErrors>Nullable</WarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ECS.Core\ECS.Core.csproj" />
    <ProjectReference Include="..\ECS.Utils\ECS.Utils.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include=".github\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
