using ECS.Interfaces;

namespace ECS.Core;

/// <summary>
/// A component that wraps a single value and fires <see cref="IComponent{TValue}.ValueChanged"/> when the value changes.
/// <c>Value</c> and <c>ValueChanged</c> are generated by <c>ComponentGenerator</c>.
/// </summary>
public abstract partial class Component<TValue> : Component, IComponent<TValue>
{
    /// <summary>
    /// Initialises the component and sets <see cref="IComponent{TValue}.Value"/> to <paramref name="initialValue"/>.
    /// </summary>
    protected Component(TValue initialValue) => this.Value = initialValue;
}
