<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Authors>Agus Garcia</Authors>
    <Company>ECS</Company>
    <CompilerGeneratedFilesOutputPath>$(BaseIntermediateOutputPath)/GeneratedFiles</CompilerGeneratedFilesOutputPath>
    <Description>A lightweight Entity Component System (ECS) framework for Godot 4 — core abstractions (Entity, Component, System), low-level utilities (object pooling, typed sets, node tracking), and ready-to-use components (velocity, rotation, height, state machine).</Description>
    <DevelopmentDependency>true</DevelopmentDependency>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <ImplicitUsings>enable</ImplicitUsings>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <LangVersion>14.0</LangVersion>
    <Nullable>enable</Nullable>
    <PackageId>ECS</PackageId>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/agusmgarcia/godot-ecs</RepositoryUrl>
    <RootNamespace>ECS</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Version>0.5.1</Version>
    <WarningsAsErrors>Nullable</WarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="GodotSharp" Version="4.7.0" />
  </ItemGroup>

  <ItemGroup>
    <None Include="../.github/README.md" Pack="true" PackagePath="/" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference 
      Include="../ECS.Generators/ECS.Generators.csproj"
      OutputItemType="Analyzer"
      ReferenceOutputAssembly="false" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="**/*.cs" Exclude="bin/**;obj/**">
      <Pack>true</Pack>
      <PackagePath>contentFiles/cs/any/ECS/Source/</PackagePath>
      <BuildAction>Compile</BuildAction>
    </Content>

    <Content Include="$(BaseIntermediateOutputPath)/GeneratedFiles/**/*.cs">
      <Pack>true</Pack>
      <PackagePath>contentFiles/cs/any/ECS/Generated/</PackagePath>
      <BuildAction>Compile</BuildAction>
    </Content>
  </ItemGroup>

  <Target Name="CreateNuGetPlaceholderFile" BeforeTargets="GenerateNuspec;Pack">
    <WriteLinesToFile File="$(IntermediateOutputPath)_._" Overwrite="true" Lines="" />
  </Target>

  <ItemGroup>
    <None Include="$(IntermediateOutputPath)_._" Pack="true" PackagePath="lib/$(TargetFramework)/_._" />
  </ItemGroup>

</Project>
