using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ECS.Generators;

/// <summary>
/// Emits <c>HideInheritedMembersAttribute</c> and, for every class annotated
/// with it, a <c>partial</c> class that seals inherited virtual members and
/// shadows non-virtual ones with <c>[EditorBrowsable(Never)]</c> overloads.
/// </summary>
[Generator]
public sealed partial class HideInheritedMembersGenerator : IIncrementalGenerator
{
    private const string AttributeFqn = "ECS.HideInheritedMembersAttribute";

    // When a class implements any of these interfaces the three Godot lifecycle
    // methods are owned by the corresponding role generator; we must not emit
    // them here to avoid duplicate-member compilation errors.
    private static readonly HashSet<string> _roleInterfaces = new(StringComparer.Ordinal)
    {
        "ECS.Interfaces.IEntity",
        "ECS.Interfaces.IComponent",
        "ECS.Interfaces.ISystem",
    };

    private const string AttributeSource = """
        // <auto-generated/>
        #nullable enable

        namespace ECS
        {
            /// <summary>
            /// Instructs the ECS source generator to shadow every inherited public
            /// member with an <c>[EditorBrowsable(Never)]</c> overload so that
            /// only ECS-specific API is visible to consumers of the package.
            /// </summary>
            /// <param name="whitelist">Member names that must NOT be hidden.</param>
            [global::System.AttributeUsage(
                global::System.AttributeTargets.Class,
                Inherited = false,
                AllowMultiple = false)]
            internal sealed class HideInheritedMembersAttribute(
                params string[] whitelist) : global::System.Attribute
            {
                public string[] Whitelist { get; } = whitelist;
            }
        }
        """;

    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
            ctx.AddSource(
                "HideInheritedMembersAttribute.g.cs",
                SourceText.From(AttributeSource, Encoding.UTF8)));

        IncrementalValuesProvider<ClassDeclarationSyntax> candidates =
            context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    AttributeFqn,
                    predicate: static (node, _) => node is ClassDeclarationSyntax,
                    transform: static (ctx, _) => (ClassDeclarationSyntax)ctx.TargetNode);

        IncrementalValueProvider<(Compilation, ImmutableArray<ClassDeclarationSyntax>)> combined =
            context.CompilationProvider.Combine(candidates.Collect());

        context.RegisterSourceOutput(combined, static (spc, source) =>
        {
            var (compilation, classes) = source;
            foreach (var classDecl in classes)
                Generate(spc, compilation, classDecl);
        });
    }

    private static void Generate(
        SourceProductionContext spc,
        Compilation compilation,
        ClassDeclarationSyntax classDecl)
    {
        var model = compilation.GetSemanticModel(classDecl.SyntaxTree);
        if (model.GetDeclaredSymbol(classDecl) is not INamedTypeSymbol classSymbol)
            return;

        // If the class implements a role interface, the lifecycle methods are
        // owned by that role's generator; exclude them from our skip-set so
        // that the role generator can emit them without conflict.
        var skipLifecycle = HasRoleInterface(classSymbol);

        var whitelist = GetWhitelist(classSymbol, AttributeFqn);
        var ownNames = GetOwnNames(classSymbol);
        var toHide = CollectMembersToHide(classSymbol, whitelist, ownNames, skipLifecycle);

        if (toHide.Count == 0)
            return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.ComponentModel;");
        sb.AppendLine();

        var ns = classSymbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : classSymbol.ContainingNamespace.ToDisplayString();

        if (ns is not null) { sb.AppendLine($"namespace {ns}"); sb.AppendLine("{"); }

        var typeParams = classSymbol.TypeParameters.Length > 0
            ? "<" + string.Join(", ", classSymbol.TypeParameters.Select(tp => tp.Name)) + ">"
            : string.Empty;

        sb.AppendLine($"    partial class {classSymbol.Name}{typeParams}");
        sb.AppendLine("    {");
        sb.AppendLine("        #region Hidden inherited members");
        sb.AppendLine();

        foreach (var mth in toHide)
            EmitMember(sb, mth);

        sb.AppendLine("        #endregion");
        sb.AppendLine("    }");
        if (ns is not null) sb.AppendLine("}");

        var hintName =
            classSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                       .Replace("global::", "")
                       .Replace("<", "[")
                       .Replace(">", "]")
            + ".HideInheritedMembers.g.cs";

        spc.AddSource(hintName, SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static bool HasRoleInterface(INamedTypeSymbol classSymbol)
    {
        foreach (var iface in classSymbol.AllInterfaces)
            if (_roleInterfaces.Contains(iface.ToDisplayString()))
                return true;
        return false;
    }
}
