using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ECS.Generators;

/// <summary>
/// Emits <c>HideInheritedMembersAttribute</c> and, for every class annotated
/// with it, a <c>partial</c> class that seals inherited virtual members and
/// shadows non-virtual ones with <c>[EditorBrowsable(Never)]</c> overloads.
/// <c>_EnterTree</c>, <c>_PhysicsProcess</c>, and <c>_ExitTree</c> additionally
/// call <c>OnInit</c>, <c>OnUpdate</c>, and <c>OnDispose</c> hooks which are
/// generated as empty <c>protected virtual</c> methods when absent.
/// </summary>
[Generator]
public sealed partial class HideInheritedMembersGenerator : IIncrementalGenerator
{
    private const string AttributeFqn = "ECS.HideInheritedMembersAttribute";

    private const string AttributeSource = """
        // <auto-generated/>
        #nullable enable

        namespace ECS
        {
            /// <summary>
            /// Instructs the ECS source generator to shadow every inherited public
            /// member with an <c>[EditorBrowsable(Never)]</c> overload so that
            /// only ECS-specific API is visible to consumers of the package.
            /// </summary>
            /// <param name="whitelist">Member names that must NOT be hidden.</param>
            [global::System.AttributeUsage(
                global::System.AttributeTargets.Class,
                Inherited = false,
                AllowMultiple = false)]
            internal sealed class HideInheritedMembersAttribute(
                params string[] whitelist) : global::System.Attribute
            {
                public string[] Whitelist { get; } = whitelist;
            }
        }
        """;

    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
            ctx.AddSource(
                "HideInheritedMembersAttribute.g.cs",
                SourceText.From(AttributeSource, Encoding.UTF8)));

        IncrementalValuesProvider<ClassDeclarationSyntax> candidates =
            context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    AttributeFqn,
                    predicate: static (node, _) => node is ClassDeclarationSyntax,
                    transform: static (ctx, _) => (ClassDeclarationSyntax)ctx.TargetNode);

        IncrementalValueProvider<(Compilation, ImmutableArray<ClassDeclarationSyntax>)> combined =
            context.CompilationProvider.Combine(candidates.Collect());

        context.RegisterSourceOutput(combined, static (spc, source) =>
        {
            var (compilation, classes) = source;
            foreach (var classDecl in classes)
                Generate(spc, compilation, classDecl);
        });
    }

    private static void Generate(
        SourceProductionContext spc,
        Compilation compilation,
        ClassDeclarationSyntax classDecl)
    {
        var model = compilation.GetSemanticModel(classDecl.SyntaxTree);
        if (model.GetDeclaredSymbol(classDecl) is not INamedTypeSymbol classSymbol)
            return;

        var whitelist = GetWhitelist(classSymbol, AttributeFqn);
        var ownNames  = GetOwnNames(classSymbol);
        var toHide    = CollectMembersToHide(classSymbol, whitelist, ownNames);

        // Determine which lifecycle hooks are missing from the class (need to be generated).
        var missingHooks = new List<string>();
        foreach (var hook in new[] { "OnInit", "OnUpdate", "OnDispose" })
            if (!ownNames.Contains(hook))
                missingHooks.Add(hook);

        // Nothing to emit at all — skip file creation.
        if (toHide.Count == 0 && missingHooks.Count == 0)
            return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.ComponentModel;");
        sb.AppendLine();

        var ns = classSymbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : classSymbol.ContainingNamespace.ToDisplayString();

        if (ns is not null) { sb.AppendLine($"namespace {ns}"); sb.AppendLine("{"); }

        var typeParams = classSymbol.TypeParameters.Length > 0
            ? "<" + string.Join(", ", classSymbol.TypeParameters.Select(tp => tp.Name)) + ">"
            : string.Empty;

        sb.AppendLine($"    partial class {classSymbol.Name}{typeParams}");
        sb.AppendLine("    {");

        // --- Hidden / sealed members region ---
        if (toHide.Count > 0)
        {
            sb.AppendLine("        #region Hidden inherited members");
            sb.AppendLine();
            foreach (var mth in toHide)
                EmitMember(sb, mth);
            sb.AppendLine("        #endregion");
        }

        // --- Generated lifecycle hooks (only those absent from the hand-written class) ---
        if (missingHooks.Count > 0)
        {
            if (toHide.Count > 0) sb.AppendLine();
            sb.AppendLine("        #region Generated lifecycle hooks");
            sb.AppendLine();
            foreach (var hook in missingHooks)
                EmitHook(sb, hook);
            sb.AppendLine("        #endregion");
        }

        sb.AppendLine("    }");
        if (ns is not null) sb.AppendLine("}");

        var hintName =
            classSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                       .Replace("global::", "")
                       .Replace("<", "[")
                       .Replace(">", "]")
            + ".HideInheritedMembers.g.cs";

        spc.AddSource(hintName, SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void EmitHook(StringBuilder sb, string hookName)
    {
        switch (hookName)
        {
            case "OnInit":
                sb.AppendLine("        /// <summary>");
                sb.AppendLine("        /// Called once after the node enters the scene tree and internal state is ready.");
                sb.AppendLine("        /// </summary>");
                sb.AppendLine("        protected virtual void OnInit() { }");
                break;
            case "OnUpdate":
                sb.AppendLine("        /// <summary>");
                sb.AppendLine("        /// Called every physics frame while the node is in the scene tree.");
                sb.AppendLine("        /// </summary>");
                sb.AppendLine("        protected virtual void OnUpdate(double delta) { }");
                break;
            case "OnDispose":
                sb.AppendLine("        /// <summary>");
                sb.AppendLine("        /// Called once before the node exits the scene tree and internal state is torn down.");
                sb.AppendLine("        /// </summary>");
                sb.AppendLine("        protected virtual void OnDispose() { }");
                break;
        }
        sb.AppendLine();
    }
}
