using System.Text;
using Microsoft.CodeAnalysis;

namespace ECS.Generators;

/// <summary>
/// Shared utilities for <see cref="EntityGenerator"/>, <see cref="ComponentGenerator"/>,
/// and <see cref="SystemGenerator"/>.
/// </summary>
internal static class RoleGeneratorHelper
{
    /// <summary>
    /// Returns the names of all members declared directly on <paramref name="classSymbol"/>.
    /// </summary>
    public static HashSet<string> GetOwnNames(INamedTypeSymbol classSymbol) =>
        new(classSymbol.GetMembers().Select(m => m.Name), StringComparer.Ordinal);

    /// <summary>
    /// Writes the auto-generated file header, namespace open, and partial class open.
    /// Sets <paramref name="ns"/> and <paramref name="indent"/> for the caller.
    /// </summary>
    public static void WriteHeader(
        StringBuilder sb,
        INamedTypeSymbol classSymbol,
        out string? ns,
        out string indent)
    {
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        ns = classSymbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : classSymbol.ContainingNamespace.ToDisplayString();

        if (ns is not null)
        {
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
            indent = "    ";
        }
        else
        {
            indent = string.Empty;
        }

        var typeParams = classSymbol.TypeParameters.Length > 0
            ? "<" + string.Join(", ", classSymbol.TypeParameters.Select(tp => tp.Name)) + ">"
            : string.Empty;

        sb.AppendLine($"{indent}partial class {classSymbol.Name}{typeParams}");
        sb.AppendLine($"{indent}{{");
    }

    /// <summary>
    /// Closes the partial class and namespace.
    /// </summary>
    public static void WriteFooter(StringBuilder sb, string? ns)
    {
        if (ns is not null)
        {
            sb.AppendLine("    }");
            sb.AppendLine("}");
        }
        else
        {
            sb.AppendLine("}");
        }
    }

    /// <summary>
    /// Builds a unique source hint name for the given class and generator suffix.
    /// </summary>
    public static string HintName(INamedTypeSymbol classSymbol, string suffix) =>
        classSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                   .Replace("global::", "")
                   .Replace("<", "[")
                   .Replace(">", "]")
        + "." + suffix;
}
