using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ECS.Generators;

/// <summary>
/// Base class for <see cref="ComponentGenerator"/>, <see cref="EntityGenerator"/>, and
/// <see cref="SystemGenerator"/>: owns the shared incremental-generator pipeline,
/// source-output scaffold, and static source-writing utilities.
/// Subclasses supply only the role-specific member emission.
/// </summary>
public abstract class RoleGenerator : IIncrementalGenerator
{
    /// <summary>Fully-qualified name of the interface that triggers this generator.</summary>
    protected abstract string TargetInterface { get; }

    /// <summary>File-name suffix for the generated hint, e.g. <c>"Component.g.cs"</c>.</summary>
    protected abstract string HintSuffix { get; }

    /// <summary>
    /// Returns <see langword="true"/> when this generator should process <paramref name="classSymbol"/>.
    /// The default implementation checks whether the class directly implements <see cref="TargetInterface"/>.
    /// Override to widen the trigger condition (e.g. to also match a generic variant of the interface).
    /// </summary>
    protected virtual bool ShouldProcess(INamedTypeSymbol classSymbol) =>
        ImplementsDirectly(classSymbol, this.TargetInterface);

    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax c && c.BaseList != null,
                transform: static (ctx, _) => (ClassDeclarationSyntax)ctx.Node)
            .Where(static c => c is not null);

        var combined = context.CompilationProvider.Combine(candidates.Collect());

        context.RegisterSourceOutput(combined, (spc, source) =>
        {
            var (compilation, classes) = source;
            foreach (var classDecl in classes)
                this.Generate(spc, compilation, classDecl);
        });
    }

    private void Generate(
        SourceProductionContext spc,
        Compilation compilation,
        ClassDeclarationSyntax classDecl)
    {
        var model = compilation.GetSemanticModel(classDecl.SyntaxTree);
        if (model.GetDeclaredSymbol(classDecl) is not INamedTypeSymbol classSymbol) return;

        if (!this.ShouldProcess(classSymbol)) return;

        var own = GetOwnNames(classSymbol);

        var sb = new StringBuilder();
        WriteHeader(sb, classSymbol, out var ns, out var indent);

        this.EmitMembers(classSymbol, own, sb, indent);

        WriteFooter(sb, ns);
        spc.AddSource(HintName(classSymbol, this.HintSuffix),
            SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    /// <summary>
    /// Emits all role-specific members into <paramref name="sb"/>.
    /// Called between the generated partial-class header and footer.
    /// </summary>
    protected abstract void EmitMembers(
        INamedTypeSymbol classSymbol,
        HashSet<string> own,
        StringBuilder sb,
        string indent);

    /// <summary>
    /// Returns <see langword="true"/> when <paramref name="classSymbol"/> directly lists
    /// <paramref name="ifaceFqn"/> in its own interface list (not inherited).
    /// </summary>
    protected static bool ImplementsDirectly(INamedTypeSymbol classSymbol, string ifaceFqn)
    {
        foreach (var iface in classSymbol.Interfaces)
            if (iface.ToDisplayString() == ifaceFqn) return true;
        return false;
    }

    /// <summary>
    /// Builds a directory-structured source hint name for the given class and generator suffix.
    /// </summary>
    public static string HintName(INamedTypeSymbol classSymbol, string suffix)
    {
        var ns = classSymbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : classSymbol.ContainingNamespace.ToDisplayString();

        var dir = ns is null ? string.Empty
            : ns.StartsWith("ECS.", StringComparison.Ordinal) ? ns.Substring(4).Replace('.', '/')
            : ns.Equals("ECS", StringComparison.Ordinal) ? string.Empty
            : ns.Replace('.', '/');

        var arity = classSymbol.TypeParameters.Length > 0
            ? "`" + classSymbol.TypeParameters.Length
            : string.Empty;

        var fileName = classSymbol.Name + arity + "." + suffix;
        return dir.Length > 0 ? dir + "/" + fileName : fileName;
    }

    private static HashSet<string> GetOwnNames(INamedTypeSymbol classSymbol) =>
        new(classSymbol.GetMembers().Select(m => m.Name), StringComparer.Ordinal);

    private static void WriteHeader(
        StringBuilder sb,
        INamedTypeSymbol classSymbol,
        out string? ns,
        out string indent)
    {
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        ns = classSymbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : classSymbol.ContainingNamespace.ToDisplayString();

        if (ns is not null)
        {
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
            indent = "    ";
        }
        else
        {
            indent = string.Empty;
        }

        var typeParams = classSymbol.TypeParameters.Length > 0
            ? "<" + string.Join(", ", classSymbol.TypeParameters.Select(tp => tp.Name)) + ">"
            : string.Empty;

        sb.AppendLine($"{indent}partial class {classSymbol.Name}{typeParams}");
        sb.AppendLine($"{indent}{{");
    }

    private static void WriteFooter(StringBuilder sb, string? ns)
    {
        if (ns is not null)
        {
            sb.AppendLine("    }");
            sb.AppendLine("}");
        }
        else
        {
            sb.AppendLine("}");
        }
    }
}
