using ECS.Interfaces;
using Godot;

namespace ECS.Components;

/// <summary>
/// ECS-aware wrapper around <see cref="Godot.AnimationPlayer"/> that implements <see cref="IComponent{TValue}"/>
/// with <c>TValue = <see cref="StringName"/>?</c>; <c>Value</c> tracks the currently playing animation name.
/// <c>Value</c> and <c>ValueChanged</c> are generated by <c>ComponentGenerator</c>.
/// </summary>
[HideInheritedMembers("GetAnimationList", "Name", "Pause", "Play", "Stop", "Owner")]
public abstract partial class AnimationPlayer : Godot.AnimationPlayer, IComponent<StringName?>
{
    /// <summary>
    /// Creates a new animation player and sets the initial <c>Value</c> to the current animation.
    /// </summary>
    public AnimationPlayer() =>
        this.Value = !string.IsNullOrEmpty(base.CurrentAnimation) ? base.CurrentAnimation : null;

    /// <summary>
    /// Called once after the component enters the scene tree and internal state is ready.
    /// </summary>
    protected virtual void OnInit()
    {
        base.AnimationFinished += this.OnAnimationFinished;
        base.AnimationStarted += this.OnAnimationStarted;
        this.OnAnimationStarted(base.CurrentAnimation);
    }

    private void OnAnimationStarted(StringName animationName) =>
        this.Value = !string.IsNullOrEmpty(animationName) ? animationName : null;

    private void OnAnimationFinished(StringName animationName) =>
        this.Value = this.Value == animationName ? null : this.Value;

    /// <summary>
    /// Called once before the component exits the scene tree and internal state is torn down.
    /// </summary>
    protected virtual void OnDispose()
    {
        this.OnAnimationFinished(base.CurrentAnimation);
        base.AnimationFinished -= this.OnAnimationFinished;
        base.AnimationStarted -= this.OnAnimationStarted;
    }
}
