namespace ECS.Interfaces;

/// <summary>
/// Extends <see cref="IComponent"/> with a typed <see cref="Value"/> property and a
/// <see cref="ValueChanged"/> event; the implementation is generated by <c>ComponentGenerator</c>.
/// </summary>
/// <typeparam name="TValue">The type of value this component wraps.</typeparam>
public interface IComponent<TValue> : IComponent
{
    /// <summary>
    /// Raised when <see cref="Value"/> is assigned a value that differs from the current one.
    /// </summary>
    event Action<TValue>? ValueChanged;

    /// <summary>
    /// The current value.
    /// </summary>
    TValue Value { get; }
}
